### ISSUE TITLE
How do you annotate the id and the bbox?

### ISSUE THREAD

**Issue by xiaojing-19** [VideoObjectSearch/RandPerson#4]
Hi,
Recently, I also want to use unity to generate some data. I want to know how you annotate the id and the bbox, because there are multi-camera and multi-person.

**Comment by Yanan-Wang-cs** [comment]
First, traverse the character element to obtain the element name and thus the ID. Then traverse the camera. Since the character has many sub-components, the position of the sub-component in the specified camera can be obtained through the “camera.WorldToScreenPoint(child.position)“ function. Thereby, the ID and key point position of the current character are obtained.

**Comment by ShengcaiLiao** [comment]
With the keypoints recorded, bbox can be obtained using the method described in the paper.

**Comment by xiaojing-19** [comment]
Thanks for your reply, I will try it. In the past few days, I tried to use the camera to render different layer and found that it consumes too much memory. Thanks again.
